In [2]:
'''
急切模式API
'''

import tensorflow as tf
import tensorflow.contrib.eager as tfe
import numpy as np

In [4]:
print("设置急切模式")
tfe.enable_eager_execution()

设置急切模式


In [5]:
print("定义constant向量")
a = tf.constant(2)
print("a = %i" % a)
b = tf.constant(3)
print("b = %i" % b)

定义constant向量
a = 2
b = 3


In [6]:
print("不使用tf.Session() 进行运算")
c = a+b
print("a+b = %i" % c)
d = a*b
print("a*b = %i" % d)

不使用tf.Session() 进行运算
a+b = 5
a*b = 6


In [8]:
print("用comstant 定义矩阵或向量")
ma = tf.constant([[1,2,3],[4,5,6],[7,8,9]],dtype=tf.float32)
print("Tensor:\n ma = %s" % ma)

mb = tf.constant([[2,2,3],[5,5,5],[8,8,8]],dtype=tf.float32)
print("Tensor:\n mb = %s" % mb)

用comstant 定义矩阵或向量
Tensor:
 ma = tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]], shape=(3, 3), dtype=float32)
Tensor:
 mb = tf.Tensor(
[[2. 2. 3.]
 [5. 5. 5.]
 [8. 8. 8.]], shape=(3, 3), dtype=float32)


In [12]:
print("矩阵运算不使用　ｔｆ．Ｓｅｓｓｉｏｎ（）")
mc= ma+mb
print("ma+mb = %s" % mc)
md = ma*mb
print("ma*mb = %s" % md)
me = tf.matmul(ma,mb)
print("矩阵相乘ma*mb = %s" % me)


矩阵运算不使用　ｔｆ．Ｓｅｓｓｉｏｎ（）
ma+mb = tf.Tensor(
[[ 3.  4.  6.]
 [ 9. 10. 11.]
 [15. 16. 17.]], shape=(3, 3), dtype=float32)
ma*mb = tf.Tensor(
[[ 2.  4.  9.]
 [20. 25. 30.]
 [56. 64. 72.]], shape=(3, 3), dtype=float32)
矩阵相乘ma*mb = tf.Tensor(
[[ 36.  36.  37.]
 [ 81.  81.  85.]
 [126. 126. 133.]], shape=(3, 3), dtype=float32)


In [ ]:
print('遍历每个元素')
for i in range(len()):
    for j in range(ma[0].shape[])